[package]
name = "ffi-wasm-editor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
core-error = { path = "../core-error" }
kernel-doc = { path = "../kernel-doc" }
kernel-scene = { path = "../kernel-scene" }
kernel-layout = { path = "../kernel-layout" }
kernel-history = { path = "../kernel-history" }

[lib]
path = "src/lib.rs"

