[package]
name = "kernel-scene"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
core-error = { path = "../core-error" }
core-id = { path = "../core-id" }
kernel-doc = { path = "../kernel-doc" }
kernel-text = { path = "../kernel-text" }
serde_json = "1"

[lib]
path = "src/lib.rs"
