import { V2_EDITOR_SCHEMA_VERSION, type SceneDoc } from "@/v2/editor/contracts";

const now = new Date().toISOString();

export const sampleSceneDoc: SceneDoc = {
  schemaVersion: V2_EDITOR_SCHEMA_VERSION,
  documentId: "v2-editor-scaffold",
  title: "NULL v2 Editor Scaffold",
  pages: [
    {
      id: "page-home",
      name: "Canvas",
      rootId: "root-frame",
      guides: [],
      nodes: [
        {
          id: "root-frame",
          kind: "frame",
          name: "Root Frame",
          parentId: null,
          children: [
            "shape-demo",
            "path-demo",
            "hero-frame",
            "sidebar-frame",
            "badge-component",
            "badge-instance",
          ],
          frame: { x: 0, y: 0, w: 1440, h: 960, rotation: 0 },
        },
        {
          id: "shape-demo",
          kind: "shape",
          name: "Brand Orb",
          parentId: "root-frame",
          frame: { x: 120, y: 140, w: 96, h: 96, rotation: 0 },
          constraints: { horizontal: "min", vertical: "min" },
          shape: {
            primitive: "ellipse",
            fill: "#2859ff",
            strokeColor: "#1d4ed8",
            strokeWidth: 2,
            cornerRadius: 0,
            opacity: 0.95,
          },
        },
        {
          id: "path-demo",
          kind: "shape",
          name: "Path Demo",
          parentId: "root-frame",
          frame: { x: 120, y: 280, w: 180, h: 120, rotation: 0 },
          constraints: { horizontal: "min", vertical: "min" },
          shape: {
            primitive: "path",
            fill: "#93c5fd",
            strokeColor: "#1d4ed8",
            strokeWidth: 3,
            cornerRadius: 0,
            opacity: 0.9,
            path: {
              closed: true,
              points: [
                { x: 0, y: 96 },
                { x: 48, y: 12 },
                { x: 108, y: 60 },
                { x: 168, y: 0 },
                { x: 180, y: 108 },
              ],
            },
          },
        },
        {
          id: "hero-frame",
          kind: "frame",
          name: "Hero Surface",
          parentId: "root-frame",
          children: ["hero-title", "hero-body"],
          frame: { x: 280, y: 120, w: 760, h: 320, rotation: 0 },
          constraints: { horizontal: "scale", vertical: "min" },
          layout: {
            direction: "vertical",
            gap: 16,
            paddingX: 40,
            paddingY: 40,
            align: "start",
            justify: "start",
          },
        },
        {
          id: "hero-title",
          kind: "text",
          name: "Title",
          parentId: "hero-frame",
          frame: { x: 320, y: 160, w: 540, h: 72, rotation: 0 },
          constraints: { horizontal: "stretch", vertical: "min" },
          text: {
            content: "Design faster. Ship clearer.",
            fontFamily: "Inter",
            fontSize: 42,
            fontWeight: 700,
            lineHeight: 52,
            letterSpacing: -0.6,
            paragraphSpacing: 0,
            align: "left",
            color: "#0f172a",
            sizing: "auto_height",
          },
        },
        {
          id: "hero-body",
          kind: "text",
          name: "Description",
          parentId: "hero-frame",
          frame: { x: 320, y: 248, w: 520, h: 88, rotation: 0 },
          constraints: { horizontal: "stretch", vertical: "min" },
          text: {
            content:
              "NULL v2 editor rebuild is moving to a Rust/WASM kernel with faster selection, cleaner layout decisions, and tighter runtime handoff.",
            fontFamily: "Inter",
            fontSize: 18,
            fontWeight: 500,
            lineHeight: 30,
            letterSpacing: 0,
            paragraphSpacing: 10,
            align: "left",
            color: "#475569",
            sizing: "auto_height",
          },
        },
        {
          id: "sidebar-frame",
          kind: "frame",
          name: "Inspector Demo",
          parentId: "root-frame",
          children: [],
          frame: { x: 1080, y: 120, w: 220, h: 520, rotation: 0 },
          constraints: { horizontal: "max", vertical: "stretch" },
        },
        {
          id: "badge-component",
          kind: "component",
          name: "Badge / Primary",
          parentId: "root-frame",
          children: ["badge-component-text"],
          frame: { x: 340, y: 500, w: 168, h: 56, rotation: 0 },
          constraints: { horizontal: "min", vertical: "min" },
          layout: {
            direction: "horizontal",
            gap: 0,
            paddingX: 18,
            paddingY: 14,
            align: "center",
            justify: "center",
          },
          component: {
            componentKey: "badge-primary",
          },
        },
        {
          id: "badge-component-text",
          kind: "text",
          name: "Badge Label",
          parentId: "badge-component",
          frame: { x: 358, y: 514, w: 132, h: 24, rotation: 0 },
          constraints: { horizontal: "stretch", vertical: "min" },
          text: {
            content: "Primary Badge",
            fontFamily: "Inter",
            fontSize: 16,
            fontWeight: 600,
            lineHeight: 24,
            letterSpacing: 0,
            paragraphSpacing: 0,
            align: "center",
            color: "#0f172a",
            sizing: "auto_height",
          },
        },
        {
          id: "badge-instance",
          kind: "instance",
          name: "Badge / Primary Copy",
          parentId: "root-frame",
          children: ["badge-instance-text"],
          frame: { x: 560, y: 500, w: 168, h: 56, rotation: 0 },
          constraints: { horizontal: "min", vertical: "min" },
          layout: {
            direction: "horizontal",
            gap: 0,
            paddingX: 18,
            paddingY: 14,
            align: "center",
            justify: "center",
          },
          instance: {
            sourceComponentId: "badge-component",
            sourceComponentKey: "badge-primary",
          },
        },
        {
          id: "badge-instance-text",
          kind: "text",
          name: "Badge Label Copy",
          parentId: "badge-instance",
          frame: { x: 578, y: 514, w: 132, h: 24, rotation: 0 },
          constraints: { horizontal: "stretch", vertical: "min" },
          text: {
            content: "Primary Badge",
            fontFamily: "Inter",
            fontSize: 16,
            fontWeight: 600,
            lineHeight: 24,
            letterSpacing: 0,
            paragraphSpacing: 0,
            align: "center",
            color: "#0f172a",
            sizing: "auto_height",
          },
        },
      ],
    },
  ],
  meta: {
    createdAt: now,
    updatedAt: now,
  },
};
