[package]
name = "kernel-text"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
core-error = { path = "../core-error" }
serde = { version = "1", features = ["derive"] }
unicode-linebreak = "0.1.5"
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"

[lib]
path = "src/lib.rs"
